### ISSUE TITLE
Dreadhorn Loot

### ISSUE THREAD

**Issue by gonculator** [UO-Eclipse/Ultima-Eclipse#50]
Dreadhorn loot is TOO MUCH. Can't sort thru half before corpse decays. Just trying to get to ingredients and tallys on bottom, cant get there. I bring trash bag and throw everything in as fast as I can and still cant see bottom. Aside from elevated drops like his mane and specials, there is 4X more loot than normal peerless.

Lady Mel is normal, can see bottom and get to ingredients almost immediately.

**Comment by discostu2u** [comment]
Suggestion:  On Broadsword/OSI peerless loot is generated by 'tiers' or in stages such that normal mobile loot is generated first (armor, jewels, etc), then ML ingredients and Talismans, so that they are placed on top of the pile, then artifacts/parrots, so they are place on top of everything.  I think if this is copied here, it would make Dreadhorn and Paroxysmus more viable, rather than losing some of these valuable because they always seem to appear on the bottom of the loot pile (ie, generated first).

**Comment by 0fallenangel** [comment]
i think you can use grid loot to not face this issue,dreadhorn will have plenty of loot anyways.

**Comment by discostu2u** [comment]
Yes, of course you can, if you're using eclipse client, but not everyone does or ever will.  Unless a single client/launcher will be required to play, this workaround doesn't solve the problem.  Pushing a single launcher/client as a requirement to play would have many advantages with respect to testing, tech support and fixes, but the reality is, it will also insure the server never has but a very small player base.  A decision has to be made to either make things compatible with the diversity of players or force players to become compatible with the way this server is ultimately going to run.  I'm not saying which, but I know exactly what will happen in either case.

**Comment by Kalan-Brock** [comment]
Lowered the loot for next restart.
