### ISSUE TITLE
Daily Task

### ISSUE THREAD

**Issue by roedar** [UO-Eclipse/Ultima-Eclipse#55]
Everytime I re-open the game my daily tasks change, ontop of that I completed a daily task before closing game and relogging showed 0 daily task points. [Additionally, is there a command to bring back the prompt up after closing it from initially logging in?]

**Comment by discostu2u** [comment]
I can verify that dailies are pretty bugged (command is [dailies btw).  Day one I got system message verification of completion of each task and the gump read daily points total as 1 and daily streak of 1/7.  Worked fine.  Day two I stopped receiving system message verification and upon completing all three it said daily pts total of 1 and daily streak of 0/7, instead of total 3 pts and streak of 2/7.  Day three I completed all three tasks and it still said total pts 1 and daily streak of 0/7 (should be total 6 and streak of 3/7.  Didn't do dailies day four because travesty was one of the tasks, thus ending my streak.
